export { default as AppMain } from './AppMain.vue'
export { default as Header } from './Header.vue'
// export { default as MobileHeader } from './header/mobile.vue'
export { default as Footer } from './Footer.vue'
// export { default as Sidebar } from './sidebar/index.vue'